### ISSUE TITLE
Error while adding external reference to revo_kart.brsar

### ISSUE THREAD

**Issue by Carbuino** [soopercool101/BrawlCrate-deprecated#22]
So basically if was following this guide here: [https://www.mariokartboards.com/threads/creating-additional-music-slots-guide.831/](https://www.mariokartboards.com/threads/creating-additional-music-slots-guide.831/) and when I get to Part 1 Step 5, the path changes from: 

`E:\Nintendo-Hacking\Wii-Stuff\BrawlBox\custom mkw\strm\r_SFC_Plains_n.brstm` 
to `E:\Nintendo-Hacking\Wii-Stuff\BrawlBox\Crate\v0.23\\tmp\04E35AC424EC8FB0`. 

Confirming the prompt then causes the program to error out and display this message with the title of System.ArgumentOutOfRangeException:

`startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at BrawlLib.SSBB.ResourceNodes.RSARExtFileNode.set_FullExtPath(String value)
   at System.Windows.Forms.SoundPackControl.mnuPath_Click(Object sender, EventArgs e)
   at System.Windows.Forms.SoundPackControl.lstSets_DoubleClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnDoubleClick(EventArgs e)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

This only seems to happen to me with BrawlCrate as Brawlbox v0.77 and v0.78 don't error out and correctly add the reference.

**Comment by fancythedeveloper** [comment]
Yea BC isn't too great with BRSARs. I recommend just using BrawlBox until stuff like this gets fixed.
